seed_everything: 42
trainer:
  logger:
      class_path: pytorch_lightning.loggers.TensorBoardLogger
      init_args:
          save_dir: tb_logs
          name: unet-l6-s8-256-spacing-res1
          log_graph: True
          default_hp_metric: False
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 10
        monitor: ${model.monitor}
        mode: min
        dirpath: checkpoints/unet-l6-s8-256-spacing-res1
        save_weights_only: True
        filename: "{epoch:02d}-{val\/loss:.2f}"
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: ${model.monitor}
        patience: 8
        verbose: True
  devices: [1]
  max_epochs: 100
  accelerator: "gpu"
  strategy: null
  log_every_n_steps: 5
model:
  model:
    class_path: monai.networks.nets.UNet
    init_args:
      spatial_dims: 3
      in_channels: 1
      out_channels: ${data.num_labels_with_bg}
      channels: [4, 8, 16, 32, 64, 128, 256]
      strides: [2, 2, 2, 2, 2, 2]
      num_res_units: 1
  learning_rate: 0.02
  sw_batch_size: ${data.crop_num_samples}
  sw_overlap: 0.1
  plateu_patience: 2
  plateu_factor: 0.1
  monitor: val/loss
data:
  supervised_dir: /mnt/HDD2/flare2022/datasets/FLARE2022/Training/FLARE22_LabeledCase50
  num_labels_with_bg: 14
  val_ratio: 0.2
  crop_num_samples: 4
  batch_size: 16
  ds_cache_type: mem
  max_workers: 4
  roi_size: [128, 128, 64]
  pixdim: [2.5, 2.5, 2.5]