seed_everything: 42
trainer:
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 10
        monitor: val_loss
        mode: min
        dirpath: checkpoints
        save_weights_only: True
        filename: "unet-l7-s4-{epoch:02d}-{val_loss:.2f}"
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: val_loss
        patience: 5
  devices: [1]
  max_epochs: 100
  accelerator: "gpu"
  strategy: null
  log_every_n_steps: 5
model:
  model:
    class_path: monai.networks.nets.UNet
    init_args:
      spatial_dims: 3
      in_channels: 1
      out_channels: ${data.num_labels_with_bg}
      channels: [4, 8, 16, 32, 64, 128, 256]
      strides: [2, 2, 2, 2, 2, 2]
  learning_rate: 0.05
  sw_batch_size: ${data.crop_num_samples}
  sw_overlap: 0.1
  plateu_patience: 2
  plateu_factor: 0.1
data:
  supervised_dir: /mnt/HDD2/flare2022/datasets/FLARE2022/Training/FLARE22_LabeledCase50/
  num_labels_with_bg: 14
  val_ratio: 0.2
  crop_num_samples: 8
  batch_size: 32
  ds_cache_type: mem
  max_workers: 4
  roi_size: [128, 128, 64]