# Semi supervised training for FLARE2022
# Coarse Model --> Fine Model
seed_everything: 42
trainer:
  logger: False
      # class_path: pytorch_lightning.loggers.TensorBoardLogger
      # init_args:
      #     save_dir: fine_logs
      #     name: c2f-fine-unet-l5-s16-256-new
      #     log_graph: True
      #     default_hp_metric: False
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 10
        monitor: ${model.monitor}
        mode: min
        dirpath: checkpoints/c2f/c2f-fine-unet-l5-s16-256-new
        save_weights_only: True
        filename: "{epoch:02d}-{val\/loss:.2f}"
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: ${model.monitor}
        patience: 40
        verbose: True
  # devices: [0] # None can not be returned in multiple GPUs
  max_epochs: 200
  accelerator: "cpu"
  log_every_n_steps: 128
  accumulate_grad_batches: 64 # Actual batch size
  val_check_interval: 0.25
  # fast_dev_run: True
model:
  coarse_model:
    class_path: monai.networks.nets.UNet
    init_args:
      spatial_dims: 3
      in_channels: 1
      out_channels: 1
      channels: [4, 8, 16, 32, 64]
      strides: [2, 2, 2, 2]
      act: relu
  fine_model:
    class_path: monai.networks.nets.UNet
    init_args:
      spatial_dims: 3
      in_channels: 1
      out_channels: ${data.num_labels_with_bg}
      channels: [16, 32, 64, 128, 256]
      strides: [2, 2, 2, 2]
      # num_res_units: 3
      act: relu
  learning_rate: 0.05
  pseudo_threshold: 0.95
  unsup_weight: 0.01
  sw_batch_size: 4
  sw_overlap: 0.25
  plateu_patience: 3
  plateu_factor: 0.2
  monitor: val/loss
  coarse_weights_path: coarse_flare_model.pt
  fine_weights_path: fine_flare_model.pt
  do_post_process: True
data:
  supervised_dir: /mnt/HDD2/flare2022/datasets/FLARE2022/Training/FLARE22_LabeledCase50
  semisupervised_dir: /mnt/HDD2/flare2022/datasets/FLARE2022/Training/Unlabeled
  predict_dir: /mnt/HDD2/flare2022/datasets/FLARE2022/Validation
  output_dir: /home/safal/naamii_togai_amigos
  do_semi: True
  semi_mu: 30
  num_labels_with_bg: 14
  val_ratio: 0.2
  crop_num_samples: 2
  batch_size: ${.crop_num_samples}
  ds_cache_type: disk
  max_workers: 4
  coarse_roi_size: [128, 128, 64]
  fine_roi_size: [192, 192, 96]
  intermediate_roi_size: [256, 256, 128]