seed_everything: 42
trainer:
  fast_dev_run: True
  logger: 
      class_path: pytorch_lightning.loggers.TensorBoardLogger
      init_args:
          save_dir: flare21/abdomen_extractor
          name: flare_21_abdomen_extractor/run1
          log_graph: True
          default_hp_metric: False
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 10
        monitor: ${model.init_args.monitor}
        mode: min
        dirpath: checkpoints/flare_21/abdomen_extractor/run1
        save_weights_only: True
        filename: "{epoch:02d}-{val\/loss:.2f}"
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: ${model.init_args.monitor}
        patience: 80
        verbose: True
  devices: [0] # None can not be returned in multiple GPUs
  max_epochs: 200
  accelerator: "gpu"
  log_every_n_steps: 256
  accumulate_grad_batches: 128 # Actual batch size
  val_check_interval: 0.5
ckpt_path: null
model:
  class_path: models.single_step_model.SingleStepModel
  init_args:
    model:
      class_path: monai.networks.nets.UNet
      init_args:
        spatial_dims: 3
        in_channels: 1
        out_channels: 1
        kernel_size: [5, 5, 3]
        up_kernel_size: [5, 5, 3]
        channels: [16, 16, 32, 32]
        strides: [2, 2, 2, 2]
        act: relu
    model_weights_path: null
    # output_threshold: 0.5
    pseudo_threshold: 0.95 # Distance from 0.5 for binary
    unsup_weight: 0.01
    learning_rate: 0.05
    sw_batch_size: 4
    sw_overlap: 0.25
    sw_mode: gaussian
    plateu_patience: 3
    plateu_factor: 0.2
    monitor: val/loss
    do_post_process: false
    connectivity: null
data:
  class_path: datamodules.single_step_datamodule.SingleStepDataModule
  init_args:
    supervised_dir: /mnt/HDD2/flare2022/datasets/FLARE2022/Training/FLARE22_LabeledCase50
    semisupervised_dir: /mnt/HDD2/flare2022/datasets/FLARE2022/Training/Unlabeled
    val_ratio: 0.2
    do_semi: False
    semi_mu: null
    crop_num_samples: 2
    batch_size: 32
    ds_cache_type: mem
    max_workers: 4
    roi_size: [128, 128, 64]
    # transform: boundingmask
    num_labels_with_bg: 14


# cfg:
#   ENVIRONMENT:
#     NUM_GPU: 1
#     DATA_BASE_DIR: 'FlareSeg/dataset/'

#   DATA_LOADER:
#     TRAIN_VAL_FOLD: 1
#     TRAIN_DB_FILE: 'db/seg_train_fold_1'
#     VAL_DB_FILE: 'db/seg_val_fold_1'
#     TEST_DB_FILE: 'db/seg_val_fold_1'
#     BAD_CASE_SERIES_IDS_TXT: 'FlareSeg/dataset/file_list/lesion_case.txt'
#     BAD_CASE_AUGMENT_TIMES: 3
#     LABEL_INDEX: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
#     LABEL_NUM: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
#     LABEL_NAME: ['Liver', 'Right Kidney', 'Spleen', 'Pancreas', 'Aorta', 'IVC', 'RAG', 'LAG', 'Gallbladder', 'Esophagus', 'Stomach', 'Duodenum', 'Left Kidney']
#     IS_COARSE: True
#     IS_NORMALIZATION_HU: True
#     IS_NORMALIZATION_DIRECTION: True
#     WINDOW_LEVEL: [-325, 325]
#     EXTEND_SIZE: 20
#     NUM_WORKER: 4
#     BATCH_SIZE: 2

#   DATA_AUGMENT:
#     IS_ENABLE: False
#     IS_RANDOM_FLIP: False
#     IS_RANDOM_ROTATE: False
#     IS_RANDOM_SHIFT: True
#     IS_RANDOM_CROP_TO_LABELS: False
#     IS_ELASTIC_TRANSFORM: False
#     IS_ADD_GAUSSIAN_NOISE: False
#     IS_CHANGE_ROI_HU: True
#     ROI_HU_RANGE: [-200, 200]
#     ROTATE_ANGLE: [-10, 10]
#     MAX_EXTEND_SIZE: 40
#     SHIFT_MAX_RATIO: 0.3

#   COARSE_MODEL:
#     META_ARCHITECTURE: 'UNet'
#     INPUT_SIZE: [160, 160, 160]
#     NUM_CLASSES: 13
#     NUM_CHANNELS: [8, 16, 32, 64, 128]
#     ENCODER_CONV_BLOCK: 'ResFourLayerConvBlock'
#     DECODER_CONV_BLOCK: 'ResTwoLayerConvBlock'
#     CONTEXT_BLOCK: None
#     NUM_DEPTH: 4
#     IS_PREPROCESS: False
#     IS_POSTPROCESS: False
#     IS_DYNAMIC_EMPTY_CACHE: False
#     WEIGHT_DIR: None

