seed_everything: 42
trainer:
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
        project: abdomen
        name: unet-l6-s4
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 10
        monitor: val_loss
        mode: min
        dirpath: playground/checkpoints
        save_weights_only: True
        filename: "unet-l6-s4-{epoch:02d}-{val_loss:.2f}"
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: val_loss
        patience: 5
  devices: [1]
  max_epochs: 600
  accelerator: "gpu"
  strategy: null
  log_every_n_steps: 18
model:
  model:
    class_path: monai.networks.nets.UNet
    init_args:
      spatial_dims: 3
      in_channels: 1
      out_channels: ${data.num_labels_with_bg}
      channels: [4, 8, 16, 32, 64, 128]
      strides: [2, 2, 2, 2, 2]
      num_res_units: 3
      norm: batch
      bias: False  # no need for bias for batch norm
  learning_rate: 0.01
  sw_batch_size: 4
  sw_overlap: 0.1
  plateu_patience: 2
  plateu_factor: 0.1
data:
  supervised_dir: /mnt/HDD2/flare2022/datasets/AbdomenCT-1K/Subtask1
  num_labels_with_bg: 5
  val_ratio: 0.2
  crop_num_samples: 4
  batch_size: 32
  ds_cache_type: disk
  max_workers: 4
  roi_size: [128, 128, 32]